### ISSUE TITLE
Add `sim2sumo` forward model to common documentation

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-sumo-sim2sumo#16]
In Equinor, there is an overview over installed ERT forward models available to the users at:
https://fmu-docs.equinor.com/docs/ert/reference/configuration/forward_model.html. E.g. `SUMO_UPLOAD` is already there.

It would be nice for the user to have the forward models in this repo documented, and added to the same list.

The link above is generated automatically based on the forward model plugin repos installed here:
https://github.com/equinor/fmu-docs/blob/master/build_docs/build_ert_docs.sh#L20

**Comment by daniel-sol** [comment]
Fixed by #29
