### ISSUE TITLE
Use res2df instead of ecl2df

### ISSUE THREAD

**Issue by yngve-sk** [equinor/fmu-sumo-sim2sumo#24]
Greeting from SCOUT! We have renamed `ecl2df` to `res2df`, so an appropriate rename here is in order. Doesn't look like many occurrences, some in `sim2sumo.py` and in `_special_treatments.py`. If there are any questions please reach out here, on slack, or whereever is more convenient for you.

**Comment by daniel-sol** [comment]
Yup, was just about to make an issue myself, this should be implemented in the next version of komodo coming come end of the year
