### ISSUE TITLE
Plugin installation in ert is broken

### ISSUE THREAD

**Issue by berland** [equinor/fmu-sumo-sim2sumo#30]
The plugin to ert is broken from the latest commit (this make all ert invocations crash when this package is installed)

There should be an integration test with ERT in this repository that asserts that the plugin is well-behaving.

Error message when running ERT with fmu-sumo-sim2sumo is installed:

`ERT crashed unexpectedly with "[Errno 20] Not a directory: '/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/fmu/sumo/sim2sumo/__init__.py/config_jobs'`

**Comment by berland** [comment]
I suspect the change in 
https://github.com/equinor/fmu-sumo-sim2sumo/commit/7e71d971f4d8089f0ef57157fbbb615684ce3b4b#diff-635398793169a2fd8386f0caca1341ac45e64df9e068694ad7eb582d43e7c7a1R63-R64
is the culprit

**Comment by equinor-ruaj** [comment]
Fixed by #31 
Also had to delete a couple of tags (and their corresponding releases) with typos: `v.0.1.7` and `v.0.1.8`. Note: extra `.` after the `v`.
Created a new tag and release `v0.1.8`
