### ISSUE TITLE
Split results when extracting vfp data

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo-sim2sumo#60]
So far sim2sumo produces only one file when extracting vfp data. User wants this split per lift curve table
This is solved in a very weird way for vfp in res2df, by giving switch --arrow, which is even weirder for sim2sumo where arrow is the norm. Suggestion is to introduce an option specific to sim2sumo called --split, but default it to True

**Comment by lindjoha** [comment]
The naming of the splitted VFP tables on sumo could be f.ex {ECLIPSE_NAME}_vfpprod_{TABLE_NB} or {ECLIPSE_NAME}_vfpinj_{TABLE_NB}.

**Comment by lindjoha** [comment]
Underscore before and after becomes _italic_. That was not the intention.
