### ISSUE TITLE
Tests are slow and prone to fail

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo-sim2sumo#67]
Should make this better:
- [x] The use of fixture case_uuid is set to run with scope function, this makes things really slow,.
It is done to ensure that tests for all versions of python run with github actions, but 
Look for improvement.
- [x] Tests keep failing in github, but not for the right reason, has something to do with competing versions of python interfering, but the first point above is supposed to fix this

**Comment by equinor-ruaj** [comment]
https://github.com/equinor/fmu-sumo-sim2sumo/pull/74 should solve this issue.

- The test teardown method was deleting test cases across runs. Changed the teardown to delete the specific case_uuid used for the current test run (defined by the `case_uuid` fixture)
- Changed the `case_uuid` fixture scope back to "session"
