### ISSUE TITLE
Update SIM2SUMO documentation

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo-sim2sumo#72]
None of the latest stuff is documented:
- [x] Handling of 3D grids
- [x] VFP splitting
- [x] ~~RFT can have md log~~
- [x] The major refactoring

**Comment by equinor-ruaj** [comment]
https://github.com/equinor/fmu-sumo-sim2sumo/pull/113 updates 3D grid docs.

**Comment by equinor-ruaj** [comment]
Based on feedback from users: https://equinor.slack.com/archives/CT986DYF3/p1732178713217549
"md_log_file" feature is not used(?) and will be removed.

**Comment by equinor-ruaj** [comment]
PR prepared if we go through with removing the "md_log_file" feature: https://github.com/equinor/fmu-sumo-sim2sumo/pull/114

**Comment by equinor-ruaj** [comment]
https://github.com/equinor/fmu-sumo-sim2sumo/pull/115 updates docs with VFP export section
