### ISSUE TITLE
Refactor common.py

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo-sim2sumo#78]
This block of code (starting from line 167 in common.py is the starting point of some serious refactoring.
````python
datafiles = find_datafiles(datafile, simconfig)
   paths = find_datafile_paths()
    logger.debug("Found datafiles %s", datafiles)
    if isinstance(datafiles, dict):
        outdict = prepare_dict_for_sendoff(datafiles, paths, grid3d)
    else:
        outdict = prepare_list_for_sendoff(
        datatype, simconfig, datafiles, paths, grid3d)
````

`find_datafiles` always returns list, so prepare_dict_for_sendoff is never called, 
`find_datafiles` calls `find_datafile_paths` etc, etc

**Comment by equinor-ruaj** [comment]
https://github.com/equinor/fmu-sumo-sim2sumo/pull/98 is a good start on this.

**Comment by equinor-ruaj** [comment]
#98 merged
