### ISSUE TITLE
Change default behavior in vfp module to both VFPPROD and VFPINJ

### ISSUE THREAD

**Issue by lindjoha** [equinor/fmu-sumo-sim2sumo#93]
If `vfp` is added to the `datatypes` under `sim2sumo` in global_variables, then only VFPPROD tables is exported. I suggest this is changed so that both VFPPROD and VFPINJ is exported.

**Comment by equinor-ruaj** [comment]
Default changed to both types: https://github.com/equinor/fmu-sumo-sim2sumo/pull/94
Waiting for nightly build before testing.

**Comment by equinor-ruaj** [comment]
Tested and confirmed change works as expected, default `vfp` exports both VFPPROD and VFPINJ.
