### ISSUE TITLE
BUG: global_variables path is not forwarded to fmu-sumo-uploader

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo-sim2sumo#96]
Custom paths to global_variables can be passed to `SIM2SUMO`:
https://github.com/equinor/fmu-sumo-sim2sumo/blob/8c075dead5a03a2e87ff7bf88d44cc19b3eb35e2/src/fmu/sumo/sim2sumo/config_jobs/SIM2SUMO#L17

However, it is never passed on to the Uploader:
https://github.com/equinor/fmu-sumo-sim2sumo/blob/8c075dead5a03a2e87ff7bf88d44cc19b3eb35e2/src/fmu/sumo/sim2sumo/common.py#L511

Result is that Uploader defaults to the standard path:
https://github.com/equinor/fmu-sumo-uploader/blob/a98c3fe498b4081f7e913252615dada00ef21bb7/src/fmu/sumo/uploader/_upload_files.py#L145

See also: https://equinor.slack.com/archives/CT986DYF3/p1726811975798499

Expected behavior:
- When custom path to global_variables is passed to SIM2SUMO, it is used throughout the code.

**Comment by equinor-ruaj** [comment]
#97 with related bugfix in [fmu-sumo-uploader](https://github.com/equinor/fmu-sumo-uploader/pull/89) should fix.
